"""table Voiture : nbPlacesDispos -> nbPlaces

Revision ID: 1985afaa9c8d
Revises: c63f9ede1618
Create Date: 2019-11-22 17:33:01.411437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1985afaa9c8d'
down_revision = 'c63f9ede1618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voiture', sa.Column('nbPlaces', sa.Integer(), nullable=True))
    op.drop_column('voiture', 'nbPlacesDispos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voiture', sa.Column('nbPlacesDispos', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('voiture', 'nbPlaces')
    # ### end Alembic commands ###
