"""table Reduction

Revision ID: 3ed17124db7e
Revises: 9c23501f8e79
Create Date: 2019-11-25 08:42:51.224594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed17124db7e'
down_revision = '9c23501f8e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reduction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('pourcentage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client', sa.Column('idReduction', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client', 'reduction', ['idReduction'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'idReduction')
    op.drop_table('reduction')
    # ### end Alembic commands ###
