"""pseudo unique

Revision ID: a65621772ae7
Revises: 3ed17124db7e
Create Date: 2019-11-25 08:49:47.070074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65621772ae7'
down_revision = '3ed17124db7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'client', ['pseudo'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='unique')
    # ### end Alembic commands ###
