"""init

Revision ID: bf9d6347702d
Revises: 
Create Date: 2019-11-23 15:39:40.328152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9d6347702d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudo', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('nom', sa.String(length=64), nullable=True),
    sa.Column('prenom', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ville', sa.String(length=64), nullable=True),
    sa.Column('nom', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('train',
    sa.Column('numTrain', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('numTrain')
    )
    op.create_table('voiture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numVoiture', sa.Integer(), nullable=True),
    sa.Column('nbPlaces', sa.Integer(), nullable=True),
    sa.Column('numTrain', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['numTrain'], ['train.numTrain'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voyage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horaireDepart', sa.DateTime(), nullable=True),
    sa.Column('horaireArrivee', sa.DateTime(), nullable=True),
    sa.Column('idGareDepart', sa.Integer(), nullable=True),
    sa.Column('idGareArrivee', sa.Integer(), nullable=True),
    sa.Column('numTrain', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idGareArrivee'], ['gare.id'], ),
    sa.ForeignKeyConstraint(['idGareDepart'], ['gare.id'], ),
    sa.ForeignKeyConstraint(['numTrain'], ['train.numTrain'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voyage_horaireArrivee'), 'voyage', ['horaireArrivee'], unique=False)
    op.create_index(op.f('ix_voyage_horaireDepart'), 'voyage', ['horaireDepart'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voyage_horaireDepart'), table_name='voyage')
    op.drop_index(op.f('ix_voyage_horaireArrivee'), table_name='voyage')
    op.drop_table('voyage')
    op.drop_table('voiture')
    op.drop_table('train')
    op.drop_table('gare')
    op.drop_table('client')
    # ### end Alembic commands ###
