"""argent, prix

Revision ID: c1b88a431134
Revises: a65621772ae7
Create Date: 2019-11-25 10:34:36.674546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b88a431134'
down_revision = 'a65621772ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('argent', sa.Integer(), nullable=True))
    op.add_column('reduction', sa.Column('prix', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reduction', 'prix')
    op.drop_column('client', 'argent')
    # ### end Alembic commands ###
