"""admin

Revision ID: e7eac9123ced
Revises: 63f989b67807
Create Date: 2019-12-03 17:41:02.627209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7eac9123ced'
down_revision = '63f989b67807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'admin')
    # ### end Alembic commands ###
